package com.lyh.guanbei.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lyh.guanbei.bean.BookBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_BEAN".
*/
public class BookBeanDao extends AbstractDao<BookBean, Long> {

    public static final String TABLENAME = "BOOK_BEAN";

    /**
     * Properties of entity BookBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Book_id = new Property(0, Long.class, "book_id", true, "_id");
        public final static Property Book_name = new Property(1, String.class, "book_name", false, "BOOK_NAME");
        public final static Property Manager_id = new Property(2, long.class, "manager_id", false, "MANAGER_ID");
        public final static Property Person_id = new Property(3, String.class, "person_id", false, "PERSON_ID");
        public final static Property Max_sum = new Property(4, String.class, "max_sum", false, "MAX_SUM");
        public final static Property Now_sum = new Property(5, String.class, "now_sum", false, "NOW_SUM");
        public final static Property Status = new Property(6, int.class, "status", false, "STATUS");
    }


    public BookBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: book_id
                "\"BOOK_NAME\" TEXT NOT NULL ," + // 1: book_name
                "\"MANAGER_ID\" INTEGER NOT NULL ," + // 2: manager_id
                "\"PERSON_ID\" TEXT," + // 3: person_id
                "\"MAX_SUM\" TEXT," + // 4: max_sum
                "\"NOW_SUM\" TEXT," + // 5: now_sum
                "\"STATUS\" INTEGER NOT NULL );"); // 6: status
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BOOK_BEAN_MANAGER_ID ON \"BOOK_BEAN\"" +
                " (\"MANAGER_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookBean entity) {
        stmt.clearBindings();
 
        Long book_id = entity.getBook_id();
        if (book_id != null) {
            stmt.bindLong(1, book_id);
        }
        stmt.bindString(2, entity.getBook_name());
        stmt.bindLong(3, entity.getManager_id());
 
        String person_id = entity.getPerson_id();
        if (person_id != null) {
            stmt.bindString(4, person_id);
        }
 
        String max_sum = entity.getMax_sum();
        if (max_sum != null) {
            stmt.bindString(5, max_sum);
        }
 
        String now_sum = entity.getNow_sum();
        if (now_sum != null) {
            stmt.bindString(6, now_sum);
        }
        stmt.bindLong(7, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookBean entity) {
        stmt.clearBindings();
 
        Long book_id = entity.getBook_id();
        if (book_id != null) {
            stmt.bindLong(1, book_id);
        }
        stmt.bindString(2, entity.getBook_name());
        stmt.bindLong(3, entity.getManager_id());
 
        String person_id = entity.getPerson_id();
        if (person_id != null) {
            stmt.bindString(4, person_id);
        }
 
        String max_sum = entity.getMax_sum();
        if (max_sum != null) {
            stmt.bindString(5, max_sum);
        }
 
        String now_sum = entity.getNow_sum();
        if (now_sum != null) {
            stmt.bindString(6, now_sum);
        }
        stmt.bindLong(7, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BookBean readEntity(Cursor cursor, int offset) {
        BookBean entity = new BookBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // book_id
            cursor.getString(offset + 1), // book_name
            cursor.getLong(offset + 2), // manager_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // person_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // max_sum
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // now_sum
            cursor.getInt(offset + 6) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookBean entity, int offset) {
        entity.setBook_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBook_name(cursor.getString(offset + 1));
        entity.setManager_id(cursor.getLong(offset + 2));
        entity.setPerson_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMax_sum(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNow_sum(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStatus(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BookBean entity, long rowId) {
        entity.setBook_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BookBean entity) {
        if(entity != null) {
            return entity.getBook_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookBean entity) {
        return entity.getBook_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
