package com.lyh.guanbei.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lyh.guanbei.bean.DeleteBook;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DELETE_BOOK".
*/
public class DeleteBookDao extends AbstractDao<DeleteBook, Long> {

    public static final String TABLENAME = "DELETE_BOOK";

    /**
     * Properties of entity DeleteBook.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Book_id = new Property(0, Long.class, "book_id", true, "_id");
    }


    public DeleteBookDao(DaoConfig config) {
        super(config);
    }
    
    public DeleteBookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DELETE_BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY );"); // 0: book_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DELETE_BOOK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DeleteBook entity) {
        stmt.clearBindings();
 
        Long book_id = entity.getBook_id();
        if (book_id != null) {
            stmt.bindLong(1, book_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DeleteBook entity) {
        stmt.clearBindings();
 
        Long book_id = entity.getBook_id();
        if (book_id != null) {
            stmt.bindLong(1, book_id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DeleteBook readEntity(Cursor cursor, int offset) {
        DeleteBook entity = new DeleteBook( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0) // book_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DeleteBook entity, int offset) {
        entity.setBook_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DeleteBook entity, long rowId) {
        entity.setBook_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DeleteBook entity) {
        if(entity != null) {
            return entity.getBook_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DeleteBook entity) {
        return entity.getBook_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
